# Generated by Django 3.1.6 on 2021-02-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practices',
            old_name='relevanc',
            new_name='relevance',
        ),
    ]
