# Generated by Django 3.1.6 on 2021-02-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_auto_20210210_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practices',
            name='relevance',
            field=models.CharField(choices=[('MEDIUM', '2'), ('HIGH', '3'), ('MINIMAL', '1')], max_length=50),
        ),
    ]
